# ---- Pipeline configuration ----


# -- Resource configuration --

# Maximum number of threads to use
nthreads: 10

# Type of paralellization to use (FORK for Linux or PSOCK for Windows)
cluster_type: FORK

# -- Pipeline configuration --

# What should your analysis be called? This is prepended to all
#   files written to disk from the pipline.
analysis_name: TCGA_LMS

# Where does the raw data live? This can be absolute or
#   relative to the directory where your Snakefile is
rawdata_dir: rawdata

# Where does the metadata live?
metadata_dir: metadata

# Where should processed data be written?
procdata_dir: procdata

# Where should the final results be written?
results_dir: results

# -- What is the assay platform?

# Options are:
# - cytoscan for: CytoscanHD, CytoScan750k
# - oncosacn for: OncoScan, OncoScan_CNV
# - snp6 fpr: GenomeWide_SNP6
# - wes for: Whole Exome Sequencing (not implemented yet!)
array_type: snp6

# -- Preprocessing configuration --

# Which reference should be used?
# Options are from BSgenome:
#   - for Affymetrix arrays: BSgenome.Hsapiens.UCSC.hg19 or
#     BSgenome.Hsapiens.UCSC.hg38
#   - for other arrays please see https://github.com/gustaveroussy/EaCoN
reference: BSgenome.Hsapiens.UCSC.hg19

# Name of the pairs file for the .CEL files, just the name, path will be
#   built using the metadata_dir.
# Must be .tsv format!
# See https://github.com/gustaveroussy/EaCoN for information
#   on the formatting the file for different array_families
pairs_file: CEL_file_pairs.tsv

# -- Segmentation configuration --

# Which segmenter should be used?
# Options are: ASCAT, FACETS or SEQUENZA
segmenter: ASCAT

# Should data smoothing be performed during segmentation; good for noisy data.
# An integer value indicating the half-window size for winsorization.
# Larger equals more smoothing, starting around 5 is recommended.
smoothk: 5

# Should be 40 for Oncoscan, 20 for Cytoscan, 60 for SNP6 and 2-10 for WES
SER_pen: 60

# Should be 0.5 for Oncoscan and WES; 1.0 for CytoscanHD and 0.25 for SNP6
nrf: 0.25

# Should be 0.9 for Oncoscan, 0.75 for all others
BAF_filter: 0.75

# --- Copy number estimation parameters

# The range of gamma values to consider when modelling allele specific copy
# number
gamma_range: [0.35, 0.95]

# --- Quality control cut-offs

# Maximum value of MAPD, metric of short-range noisiness; recommendation for
# FFPE samples is 0.3
mapd: 0.4

# Maximum value of ndWavinessSD, a metric of long-range noisiness
ndwavinesssd: 0.3

# Minimum SNPQC, a metric to evaluate the quality of BAF calls for the data;
# recommended cut-off is above 26; for FFPE samples, this criteria may be too
# strict, set to 0
snpqc: 0

# Minimum cellularity (proportion tumour) for sample inclusion; set this to 0
# if samples have already been confirmed to be pure by a pathologist
# WARNING: samples with NA cellularity are dropped when cellularity > 0!
cellularity: 0

# ---- Custom total copy number cut-offs

# copy number:log2r cut-off list
# The names of each item are appended to the output files, to allow multiple
#   cut-offs in a single run
# Cut-offs are specified as ranges, with the lower range being exclusive and
#   the upper range being inclusive (e.g., (lower, upper] in mathematical
#   notation)
# NOTE: had to use 100000 instead of infinity due to bug passing inf values
#   into R scripts with Snakemake
tcn_cutoffs: {
  50_pct: {0: [-1000000.0, -0.8], 1: [-0.8, -0.33], 2: [-0.33, 0.26],
    3: [0.26, 0.47], 4: [0.47, 1000000.0]},
  90_pct: {0: [-1000000.0, -2.66], 1: [-2.66, -0.69], 2: [-0.69, 0.43],
    3: [0.43, 0.74], 4: [0.74, 1000000.0]}
}