# ---- Pipeline configuration ----

# -- Resource configuration --

# Maximum number of threads to use
nthreads: 12

# -- Pipeline configuration --

# What should your analysis be called? This is prepended to all
#   files written to disk from the pipline.
analysis_name: vdr_LMS

# Where does the raw data live? This can be absolute or
#   relative to the directory where your Snakefile is
rawdata_dir: rawdata

# Where does the metadata live?
metadata_dir: metadata

# Where should processed data be written?
procdata_dir: procdata

# Where should the final results be written?
results_dir: results

# What type of array data?
# Options are: CytoscanHD_Array, CytoScan750k_Array, OncoScan_CNV...
# NOTE: Be careful to match the name with the output of EaCoN or the rules will fail
# > this includes matching case!
array_type: OncoScan_CNV

# -- Preprocessing configuration --

# Which reference should be used?
# Options are from BSgenome: 
#   - for Cytoscan arrays: BSgenome.Hsapiens.UCSC.hg19 or 
#     BSgenome.Hsapiens.UCSC.hg38
#   - for other arrays please see https://github.com/gustaveroussy/EaCoN
reference: BSgenome.Hsapiens.UCSC.hg19

# Name of the pairs file for the .CEL files, just the name, path will be
#   built using the metadata_dir.
# See https://github.com/gustaveroussy/EaCoN for information
#   on the formatting the file for different array_families
pairs_file: CEL_file_pairs.tsv

# -- Segmentation configuration --

# Which segmenter should be used?
# Options are: ASCAT, FACETS or SEQUENZA
segmenter: ASCAT

# Should data smoothing be performed during segmentation; good for noisy data.
# An integer value indicating the half-window size for winsorization. 
# Larger equals more smoothing, starting around 5 is recommended.
smoothk: None

# Should be 40 for Oncoscan, 20 for Cytoscan, 60 for SNP6 and 2-10 for WES
SER_pen: 20

# Should be 0.5 for Oncoscan and WES; 1.0 for CytoscanHD and 0.25 for SNP6
nrf: 0.5

# Should be 0.9 for Oncoscan, 0.75 for all others
BAF_filter: 0.9

# --- Copy number estimation parameters

# The range of gamma values to consider when modelling allele specific copy number
gamma_range: [0.35, 0.95]

# --- Feature selection parameters

# Should the sex chromosomes be removed from the feature selection?
drop_sex: true

# Creates on or more subsets of the CNV for each number in feature_numbers
# These are selected based on ordering by row-wise median absolute deviance (mad)
feature_numbers: [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 2000, 3000]
